name: Deploy S3 Storage with Terraform

on:
  push:
    branches:
      - s3-storage

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: List files Before Deployment (debug)
        run: |
          echo "ðŸ“‚ Listing project files:"
          ls -R

      - name: Initialize Terraform
        run: terraform -chdir=terraform init -var-file="env/dev/terraform-dev.tfvars"
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Plan Terraform
        run: terraform -chdir=terraform plan -var-file="env/dev/terraform-dev.tfvars"
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Apply Terraform
        run: terraform -chdir=terraform apply -auto-approve -var-file="env/dev/terraform-dev.tfvars"
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: List files (debug)
        run: |
          echo "ðŸ“‚ Listing project files:"
          ls -R
          